name: parallel-tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
        phpunit:
          - "9.x"
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - true
        include:
          - phpunit: "9.x"
            collision: "^6.4"
            paratest: "^6.4"

    name: PHP${{ matrix.php }} with PHPUnit${{ matrix.phpunit }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install PHPUnit ${{ matrix.phpunit }}
        run: |
          composer require "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
          composer require "nunomaduro/collision:${{ matrix.collision }}" "brianium/paratest:${{ matrix.paratest }}" --dev --no-interaction --no-update

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Execute tests (with deprecations)
        run: ./testbench package:test --parallel --exclude-group commander
        if: matrix.dependencies == 'highest' && matrix.phpunit == '10.x'

      - name: Execute tests (with deprecations)
        run: ./testbench package:test --parallel --exclude-group commander -c phpunit9.xml
        if: matrix.dependencies == 'highest' && matrix.phpunit == '9.x'

      - name: Execute tests (without deprecations)
        run: ./testbench package:test --parallel --exclude-group commander,deprecations
        env:
          TESTBENCH_CONVERT_DEPRECATIONS_TO_EXCEPTIONS: false
        if: matrix.dependencies != 'highest'
